name: Build Library

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-library.yml'
      - 'src/**'
      - '*.json'
      - '*.js'
      - '*.jsx'
      - '*.ts'
      - '*.tsx'
      - '*.lock'
  pull_request:
    paths:
      - '.github/workflows/build-library.yml'
      - 'src/**'
      - '*.json'
      - '*.js'
      - '*.jsx'
      - '*.ts'
      - '*.tsx'
      - '*.lock'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Build package
        run: yarn prepare